# .github/workflows/main_IAMFrontEndApp.yml
name: Build and deploy Node.js app to Azure Web App – IAMFrontEndApp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read     # checkout
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install / build / test
        run: |
          npm ci
          npm run build --if-present
          npm test       --if-present

      - name: Zip artefact
        run: zip -r release.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.webapp-url }}
    permissions:
      id-token: write    # required by the Web Apps Deploy action
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app

      - run: unzip release.zip

      # 🚫  NO azure/login HERE  🚫

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name:        'IAMFrontEndApp'
          slot-name:       'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package:         .
